import '@/app/globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Renderizado',
  description: 'Generated by create next app'
}

export default async function RootLayout({ children }) {


  return (
    <html lang="en">
      <body className={`${inter.className} bg-cover bg-center bg-white min-h-screen flex flex-col`} >
      <a href="/" className='text-5xl text-center'>🏠</a>
      <h1 className="text-3xl font-bold mb-4 text-center">Renderizado</h1>
          {children}
      </body>
    </html>
  )
}
